CREATE SEQUENCE s1 START WITH 10 MINVALUE 5 INCREMENT BY 5;
CREATE SEQUENCE s2 START WITH 250 MINVALUE 200 MAXVALUE 300;
CREATE SEQUENCE s3 START WITH 1 MAXVALUE 2 NOCACHE;
CREATE SEQUENCE s4 START WITH -1 INCREMENT BY -1 MINVALUE -1000 MAXVALUE -1;
CREATE TABLE t (id bigint NOT NULL DEFAULT nextval(s1), PRIMARY KEY (id));
