CREATE SEQUENCE s1 START WITH 1;
CREATE SEQUENCE s2 START WITH 1 MINVALUE 1 MAXVALUE 100;
CREATE SEQUENCE s3 START WITH 1 NOCACHE;
SELECT NEXTVAL(s3), NEXTVAL(s3), NEXTVAL(s3);
CREATE SEQUENCE s4 START WITH -5 INCREMENT BY -1 MINVALUE -10 MAXVALUE -5;
CREATE TABLE t (id bigint NOT NULL, PRIMARY KEY (id));
