import {
  schemaSnapshotSchema,
  tableDefSchema,
  type ColumnKind,
  type SqlDialect,
} from '@joinery/core';
import { describe, expect, it } from 'vitest';

import { canSort, columnFromMeta, describeColumns, kindForDataType, parseEnumLabels } from '../src';
import { itemsFor } from './fixtures';

describe('kindForDataType', () => {
  const cases: [SqlDialect, string, ColumnKind][] = [
    ['postgres', 'integer', 'integer'],
    ['postgres', 'smallint', 'integer'],
    ['postgres', 'bigint', 'bigint'],
    ['postgres', 'numeric(10,2)', 'decimal'],
    ['postgres', 'double precision', 'float'],
    ['postgres', 'character varying(255)', 'string'],
    ['postgres', '"char"', 'string'],
    ['postgres', 'timestamp(3) without time zone', 'datetime'],
    ['postgres', 'timestamp with time zone', 'timestamp'],
    ['postgres', 'time(6) with time zone', 'time'],
    ['postgres', 'interval year to month', 'interval'],
    ['postgres', 'jsonb', 'json'],
    ['postgres', 'uuid', 'uuid'],
    ['postgres', 'bytea', 'binary'],
    ['postgres', 'integer[]', 'array'],
    ['postgres', 'point', 'geometry'],
    ['postgres', 'public.geometry(Point,4326)', 'geometry'],
    ['postgres', 'int4', 'integer'],
    ['postgres', 'timestamptz', 'timestamp'],
    ['postgres', 'public.unknown_type', 'unknown'],
    ['mysql', 'int unsigned', 'integer'],
    ['mysql', 'bigint(20) unsigned', 'bigint'],
    ['mysql', 'tinyint(1)', 'boolean'],
    ['mysql', 'tinyint(4)', 'integer'],
    ['mysql', 'decimal(10,2) unsigned', 'decimal'],
    ['mysql', 'double', 'float'],
    ['mysql', 'datetime(6)', 'datetime'],
    ['mysql', 'timestamp', 'timestamp'],
    ['mysql', 'varbinary(16)', 'binary'],
    ['mysql', 'longtext', 'string'],
    ['mysql', "enum('a','b')", 'enum'],
    ['mysql', "set('a','b')", 'enum'],
    ['mysql', 'json', 'json'],
    ['mysql', 'multipolygon', 'geometry'],
    ['mariadb', 'uuid', 'uuid'],
    ['mariadb', 'inet6', 'string'],
    ['mysql', 'mystery', 'unknown'],
  ];
  it.each(cases)('%s %s → %s', (dialect, type, kind) => {
    expect(kindForDataType(type, dialect)).toBe(kind);
  });
});

describe('describeColumns', () => {
  it('reads limits, flags and read-only reasons from the snapshot', () => {
    const { columns } = itemsFor('mysql');
    const col = (name: string) => columns.find((c) => c.name === name)!;
    expect(col('name')).toMatchObject({ kind: 'string', length: 50, nullable: true });
    expect(col('price')).toMatchObject({ kind: 'decimal', precision: 10, scale: 2 });
    expect(col('active')).toMatchObject({ kind: 'boolean', booleanLike: true });
    expect(col('feeling')).toMatchObject({ kind: 'enum', enumValues: ['sad', 'ok', 'happy'] });
    expect(col('flags')).toMatchObject({
      kind: 'enum',
      multiple: true,
      enumValues: ['a', 'b', 'c'],
    });
    expect(col('qty')).toMatchObject({ hasDefault: true, nullable: false });
    expect(col('total')).toMatchObject({
      generated: true,
      readOnly: 'The column is generated by the server',
    });
    expect(col('name')).toMatchObject({ charset: 'utf8mb4', collation: 'utf8mb4_0900_ai_ci' });
  });

  it('resolves PostgreSQL enums and domains from the snapshot, and array elements', () => {
    const snapshot = schemaSnapshotSchema.parse({
      engine: 'postgres',
      database: 'db',
      capturedAt: '2026-09-29T00:00:00Z',
      schemas: [
        {
          name: 'app',
          types: [
            { name: 'mood', kind: 'enum', values: ['sad', 'ok'], definition: '' },
            {
              name: 'posint',
              kind: 'domain',
              definition: 'CREATE DOMAIN app.posint AS integer CHECK (VALUE > 0)',
            },
          ],
        },
      ],
    });
    const table = tableDefSchema.parse({
      name: 't',
      columns: [
        { name: 'm', ordinal: 1, dataType: 'app.mood', nullable: true },
        { name: 'p', ordinal: 2, dataType: 'app.posint', nullable: true },
        { name: 'ms', ordinal: 3, dataType: 'app.mood[]', nullable: true },
        {
          name: 'id',
          ordinal: 4,
          dataType: 'integer',
          nullable: false,
          identity: { generation: 'always' },
        },
        {
          name: 's',
          ordinal: 5,
          dataType: 'integer',
          nullable: false,
          default: "nextval('app.t_s_seq'::regclass)",
        },
      ],
    });
    const [m, p, ms, id, s] = describeColumns(table, {
      dialect: 'postgres',
      snapshot,
      schema: 'app',
    });
    expect(m).toMatchObject({ kind: 'enum', enumValues: ['sad', 'ok'] });
    expect(p).toMatchObject({ kind: 'integer' });
    expect(ms).toMatchObject({
      kind: 'array',
      element: { kind: 'enum', enumValues: ['sad', 'ok'] },
    });
    expect(id).toMatchObject({
      autoIncrement: true,
      readOnly: 'The column is GENERATED ALWAYS AS IDENTITY',
    });
    expect(s).toMatchObject({ autoIncrement: true, hasDefault: true });
    expect(s!.readOnly).toBeUndefined();
  });

  it('recognises MariaDB JSON columns by their json_valid check', () => {
    const table = tableDefSchema.parse({
      name: 'docs',
      columns: [{ name: 'body', ordinal: 1, dataType: 'longtext', nullable: true }],
      checks: [{ name: 'body', expression: 'json_valid(`body`)' }],
    });
    expect(describeColumns(table, { dialect: 'mariadb' })[0]!.kind).toBe('json');
  });

  it('parses enum labels with doubled quotes and escapes', () => {
    expect(parseEnumLabels("'a','b''c','d\\\\e',''")).toEqual(['a', "b'c", 'd\\e', '']);
  });

  it('builds columns from result metadata', () => {
    expect(
      columnFromMeta({ name: 'flag', nativeType: 'tinyint(1)', kind: 'integer' }, 'mysql'),
    ).toMatchObject({ kind: 'boolean', booleanLike: true, nullable: true });
    expect(
      columnFromMeta(
        { name: 'n', nativeType: 'numeric(12,3)', kind: 'decimal', nullable: false },
        'postgres',
      ),
    ).toMatchObject({ kind: 'decimal', precision: 12, scale: 3, nullable: false });
    expect(
      columnFromMeta({ name: 'x', nativeType: 'oid:99999', kind: 'enum' }, 'postgres').kind,
    ).toBe('enum');
  });

  it('knows which PostgreSQL types cannot be sorted', () => {
    const { columns } = itemsFor('postgres');
    const col = (name: string) => columns.find((c) => c.name === name)!;
    expect(canSort(col('raw'), 'postgres')).toBe(false);
    expect(canSort(col('doc'), 'postgres')).toBe(true);
    expect(canSort(col('name'), 'postgres')).toBe(true);
  });
});
