import type { Session } from '@joinery/core';
import { expect, test, type Locator, type Page } from '@playwright/test';

import { launchApp, type LaunchedApp } from './app';
import { connect, query, scratchDatabase } from './db';

/**
 * The table data view and the table designer against a real PostgreSQL server (spec §7, §8):
 * open a table's rows, filter and sort them on the server, stage an edit, an insert and a
 * delete, review the SQL and apply it in one transaction; a conflicting change made by someone
 * else; and a table created, altered and browsed through the designer.
 */

const PG_URL = process.env['JOINERY_TEST_POSTGRES_URL'];
const NAME = 'E2E Tables';

test.skip(!PG_URL, 'Set JOINERY_TEST_POSTGRES_URL to run the end-to-end tests');

test.describe.configure({ mode: 'serial' });

let launched: LaunchedApp | undefined;
let page: Page;
let database: Awaited<ReturnType<typeof scratchDatabase>> | undefined;
let direct: Session | undefined;

test.beforeAll(async () => {
  database = await scratchDatabase(PG_URL!);
  direct = await connect(PG_URL!, database.name);
  await query(direct, `CREATE TABLE customers (id integer PRIMARY KEY, name text NOT NULL)`);
  await query(direct, `INSERT INTO customers VALUES (1, 'Ada'), (2, 'Grace')`);
  await query(
    direct,
    `CREATE TABLE items (
       id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       name text NOT NULL,
       qty integer NOT NULL DEFAULT 0,
       price numeric(10,2),
       customer_id integer REFERENCES customers (id),
       note text
     )`,
  );
  await query(
    direct,
    `INSERT INTO items (name, qty, price, customer_id)
     SELECT 'item ' || g, g, g * 1.5, 1 + g % 2 FROM generate_series(1, 30) g`,
  );
  await query(direct, `CREATE TABLE events (id bigint PRIMARY KEY, label text NOT NULL)`);
  await query(direct, `INSERT INTO events SELECT g, 'event ' || g FROM generate_series(1, 1200) g`);
  await query(direct, `ANALYZE events`);
  launched = await launchApp();
  page = launched.page;
});

test.afterAll(async () => {
  await launched?.close();
  await direct?.close();
  await database?.drop();
});

function treeRow(text: string): Locator {
  return page.locator('[data-tree-row]').filter({ has: page.getByText(text, { exact: true }) });
}

function panel(testId: string): Locator {
  return page.getByTestId(testId).filter({ visible: true });
}

/** A grid cell through Glide's accessibility table (the first data column is 1). */
function cell(column: number, row: number): Locator {
  return panel('table-data-panel').getByTestId(`glide-cell-${column + 1}-${row}`);
}

/**
 * The grid is a canvas: a cell is found from the row marker width (32 px under 100 rows), the
 * header and row heights (28 and 26 px) and the initial column widths of the items table.
 */
const WIDTHS = [100, 200, 100, 120, 136, 200];
const MARKER = 32;

async function gridPoint(column: number, row: number): Promise<{ x: number; y: number }> {
  // Glide's scroller lies over the canvas and takes the pointer events.
  const box = await panel('table-data-panel').getByTestId('data-grid-canvas').boundingBox();
  if (!box) throw new Error('The grid is not on screen');
  const left = MARKER + WIDTHS.slice(0, column).reduce((sum, w) => sum + w, 0);
  const y = row < 0 ? 14 : 28 + 26 * row + 13;
  return { x: box.x + left + (WIDTHS[column] ?? 100) / 2, y: box.y + y };
}

async function selectCell(column: number, row: number): Promise<void> {
  const { x, y } = await gridPoint(column, row);
  await page.mouse.click(x, y);
  // Glide focuses the grid (its accessibility cell) on the next animation frame; keys go
  // elsewhere until then.
  // A click on the cell already selected opens its editor instead.
  const canvas = panel('table-data-panel').getByTestId('data-grid-canvas');
  const editor = page.getByTestId('cell-editor');
  await expect
    .poll(
      async () =>
        (await editor.isVisible()) ||
        (await canvas.evaluate((element) => element.contains(document.activeElement))),
    )
    .toBe(true);
}

async function clickHeader(column: number): Promise<void> {
  const { x, y } = await gridPoint(column, -1);
  await page.mouse.click(x, y);
}

async function editCell(column: number, row: number, text: string): Promise<void> {
  await selectCell(column, row);
  const editor = page.getByTestId('cell-editor');
  if (!(await editor.isVisible())) await page.keyboard.press('Enter');
  await expect(editor).toBeVisible();
  const input = editor.getByRole('textbox').first();
  // A click (not only fill) proves the editor is on top of the grid, where the user can reach it.
  await input.click();
  await input.fill(text);
  await input.press('Enter');
  await expect(editor).toBeHidden();
}

async function openTable(table: string): Promise<void> {
  await treeRow(table).dblclick();
  await expect(panel('table-data-panel')).toBeVisible();
}

async function setFilter(column: string, operator: string, value: string): Promise<void> {
  const bar = panel('table-data-panel').getByTestId('filter-bar');
  const clear = bar.getByRole('button', { name: 'Clear' });
  if (await clear.isEnabled()) await clear.click();
  await bar.getByRole('button', { name: 'Add condition' }).click();
  const condition = bar.getByTestId('filter-condition').last();
  await condition.getByLabel('Column').selectOption(column);
  await condition.getByLabel('Operator').selectOption(operator);
  await condition.getByLabel('Value').fill(value);
  await bar.getByRole('button', { name: 'Apply filter' }).click();
}

test('connects and opens a table from the explorer', async () => {
  await page.getByRole('button', { name: 'New connection' }).click();
  const dialog = page.getByRole('dialog', { name: 'New connection' });
  await dialog.getByLabel('Paste a URI to fill the form').fill(database!.url);
  await dialog.getByRole('button', { name: 'Fill from URI' }).click();
  // Main parses the URI asynchronously; typing before it answers races the fill.
  await expect(dialog.getByText('Filled from the URI')).toBeVisible();
  await dialog.getByLabel('Name').fill(NAME);
  await dialog.getByLabel('TLS').selectOption('disable');
  await dialog.getByLabel('Password storage').selectOption('session');
  await dialog.getByRole('button', { name: 'Save' }).click();
  await expect(dialog).toBeHidden();

  const profile = page.getByRole('treeitem', { name: NAME });
  await profile.locator('[data-tree-row]').first().click();
  await treeRow(database!.name).click();
  await treeRow('public').click();
  await treeRow('Tables').click();
  await openTable('items');

  await expect(panel('table-data-panel').getByTestId('table-row-count')).toHaveText(
    '30 rows loaded',
  );
  await expect(cell(1, 0)).toHaveText('item 1');
  await expect(cell(3, 0)).toHaveText('1.50');
  // Every row fits in the first page, so the total is known without counting.
  await expect(panel('table-data-panel').getByTestId('table-total')).toHaveText('· 30 in total');
});

test('sorts on the server by clicking a header', async () => {
  await clickHeader(1);
  // Text order: item 1, item 10, item 11...
  await expect(cell(1, 1)).toHaveText('item 10');
  await clickHeader(1);
  await expect(cell(1, 0)).toHaveText('item 9');
  // A third click removes the sort: back to key order.
  await clickHeader(1);
  await expect(cell(1, 0)).toHaveText('item 1');
});

test('filters with the builder and with a raw WHERE condition', async () => {
  await setFilter('qty', '>=', '25');
  const count = panel('table-data-panel').getByTestId('table-row-count');
  await expect(count).toHaveText('6 rows loaded');
  await expect(cell(1, 0)).toHaveText('item 25');

  const bar = panel('table-data-panel').getByTestId('filter-bar');
  await bar.getByRole('radio', { name: 'WHERE' }).click();
  const where = bar.getByLabel('WHERE condition');
  await where.fill('qty < 3; drop table items');
  await bar.getByRole('button', { name: 'Apply filter' }).click();
  await expect(bar.getByRole('alert')).toContainText('Only one condition is allowed');
  await where.fill('qty < 3');
  await where.press('Enter');
  await expect(count).toHaveText('2 rows loaded');

  await bar.getByRole('button', { name: 'Clear' }).click();
  await expect(count).toHaveText('30 rows loaded');
  await bar.getByRole('radio', { name: 'Builder' }).click();
});

test('stages an edit, an insert and a delete, and applies them in one transaction', async () => {
  await setFilter('id', '<=', '3');
  const view = panel('table-data-panel');
  await expect(view.getByTestId('table-row-count')).toHaveText('3 rows loaded');

  await editCell(1, 0, 'renamed item');
  await expect(cell(1, 0)).toHaveText('renamed item');

  await view.getByRole('button', { name: 'Add row' }).click();
  await editCell(1, 3, 'new item');
  await editCell(2, 3, '7');

  await selectCell(0, 1);
  await view.getByRole('button', { name: 'Delete rows' }).click();
  await expect(view.getByTestId('pending-changes')).toHaveText('1 edited · 1 new · 1 deleted');

  // Undo and redo the delete.
  await view.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(view.getByTestId('pending-changes')).toHaveText('1 edited · 1 new');
  await view.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect(view.getByTestId('pending-changes')).toHaveText('1 edited · 1 new · 1 deleted');

  await view.getByRole('button', { name: /^Apply \(/ }).click();
  const dialog = page.getByRole('dialog', { name: 'Apply changes' });
  const preview = dialog.getByTestId('apply-preview');
  await expect(preview).toContainText(`DELETE FROM "public"."items" WHERE "id" = 2`);
  await expect(preview).toContainText(
    `UPDATE "public"."items" SET "name" = 'renamed item' WHERE "id" = 1 AND "name" = 'item 1'`,
  );
  await expect(preview).toContainText(
    `INSERT INTO "public"."items" ("name", "qty") VALUES ('new item', 7)`,
  );
  await dialog.getByRole('button', { name: 'Apply', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(view.getByTestId('table-notice')).toContainText(
    'Applied: 1 updated, 1 inserted, 1 deleted',
  );
  await expect(view.getByTestId('pending-changes')).toHaveCount(0);

  // The server has it: directly, and through a query tab in the app.
  expect(await query(direct!, `SELECT name FROM items WHERE id = 1`)).toEqual([['renamed item']]);
  expect(await query(direct!, `SELECT count(*)::int FROM items WHERE id = 2`)).toEqual([[0]]);
  expect(await query(direct!, `SELECT qty FROM items WHERE name = 'new item'`)).toEqual([[7]]);
  await page.getByRole('button', { name: 'New query' }).click();
  const editor = page.getByTestId('sql-editor').last();
  await editor.click();
  await page.keyboard.type(`select * from items where name in ('renamed item', 'new item')`);
  await page.keyboard.press('ControlOrMeta+Enter');
  await expect(page.getByTestId('row-count').filter({ visible: true })).toHaveText('2 rows');
  // Back to the data view: opening the table again focuses the view already open.
  await openTable('items');
});

test('reports a conflict when another session changed the row, and offers to reload', async () => {
  const view = panel('table-data-panel');
  // Still filtered to id <= 3 from the previous test. Applying the same filter again would
  // reload the rows with nothing visible changing, so an edit could land mid-reload.
  await expect(view.getByTestId('table-row-count')).toHaveText('3 rows loaded');
  await expect(cell(1, 0)).toHaveText('renamed item');
  await editCell(1, 0, 'mine');
  await query(direct!, `UPDATE items SET name = 'theirs' WHERE id = 1`);

  await view.getByRole('button', { name: /^Apply \(/ }).click();
  const dialog = page.getByRole('dialog', { name: 'Apply changes' });
  await dialog.getByRole('button', { name: 'Apply', exact: true }).click();
  await expect(dialog.getByTestId('apply-error')).toContainText(
    'was changed or deleted by someone else since it was loaded; nothing was saved',
  );
  expect(await query(direct!, `SELECT name FROM items WHERE id = 1`)).toEqual([['theirs']]);
  await dialog.getByRole('button', { name: 'Discard and reload' }).click();
  await expect(dialog).toBeHidden();
  await expect(cell(1, 0)).toHaveText('theirs');
  await expect(view.getByTestId('pending-changes')).toHaveCount(0);
});

test('pastes rows into existing and new rows, marking cells that do not fit', async () => {
  const view = panel('table-data-panel');
  await expect(cell(1, 1)).toHaveText('item 3');
  await selectCell(1, 1);
  // What Excel or Google Sheets put on the clipboard: tab-separated cells, one row per line.
  await page.evaluate(() => {
    const data = new DataTransfer();
    data.setData('text/plain', 'pasted a\t5\npasted b\tlots\n');
    document.activeElement?.dispatchEvent(
      new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }),
    );
  });
  await expect(view.getByTestId('pending-changes')).toHaveText('1 edited · 1 new');
  await expect(view.getByTestId('table-notice')).toContainText('1 cell could not be read');
  await expect(cell(1, 1)).toHaveText('pasted a');
  await expect(cell(2, 1)).toHaveText('5');
  await expect(cell(1, 2)).toHaveText('pasted b');
  await selectCell(2, 2);
  await expect(view.getByTestId('cell-error')).toHaveText('Not pasted: Expected a whole number');
  await view.getByRole('button', { name: 'Discard' }).click();
  await expect(view.getByTestId('pending-changes')).toHaveCount(0);
  await expect(cell(1, 1)).toHaveText('item 3');
});

test('creates a table in the designer, renames and adds a column, and browses it', async () => {
  const tables = treeRow('Tables');
  await tables.hover();
  await tables.getByRole('button', { name: 'Actions' }).click();
  await page.getByRole('menuitem', { name: 'New table…', exact: true }).click();

  const designer = panel('table-designer');
  await expect(designer).toBeVisible();
  await designer.getByLabel('Table name').fill('e2e_notes');
  await designer.getByRole('button', { name: 'Add column' }).click();
  await designer.getByLabel('Column 2 name').fill('title');
  await designer.getByLabel('Column 2 type').fill('text');
  await designer.getByRole('button', { name: 'Save' }).click();

  let review = page.getByRole('dialog', { name: 'Review and save' });
  await expect(review.getByTestId('design-script')).toContainText(
    'CREATE TABLE "public"."e2e_notes"',
  );
  await review.getByRole('button', { name: 'Run script' }).click();
  await expect(review).toBeHidden();
  await expect(designer.getByTestId('designer-notice')).toContainText('Saved e2e_notes');
  await expect(treeRow('e2e_notes')).toBeVisible();

  // Rename title → heading (a RENAME, not a drop and add) and add a body column.
  await designer.getByLabel('Column 2 name').fill('heading');
  await designer.getByRole('button', { name: 'Add column' }).click();
  await designer.getByLabel('Column 3 name').fill('body');
  await designer.getByLabel('Column 3 type').fill('text');
  await designer.getByRole('button', { name: 'Save' }).click();
  review = page.getByRole('dialog', { name: 'Review and save' });
  const script = review.getByTestId('design-script');
  await expect(script).toContainText(
    'ALTER TABLE "public"."e2e_notes" RENAME COLUMN "title" TO "heading"',
  );
  await expect(script).toContainText('ALTER TABLE "public"."e2e_notes" ADD COLUMN "body" text');
  await expect(script).not.toContainText('DROP COLUMN');
  await review.getByRole('button', { name: 'Run script' }).click();
  await expect(review).toBeHidden();

  const columns = await query(
    direct!,
    `SELECT column_name FROM information_schema.columns WHERE table_name = 'e2e_notes' ORDER BY ordinal_position`,
  );
  expect(columns).toEqual([['id'], ['heading'], ['body']]);

  await designer.getByRole('button', { name: 'Open data' }).click();
  const data = panel('table-data-panel');
  const headers = data.getByTestId('data-grid-canvas').locator('th');
  await expect(headers).toHaveText(['🔑 id', 'heading', 'body']);
  await expect(data.getByTestId('table-row-count')).toHaveText('0 rows loaded');
});

test('estimates the total, counts exactly and loads pages as the grid scrolls', async () => {
  await openTable('events');
  const view = panel('table-data-panel');
  const count = view.getByTestId('table-row-count');
  const total = view.getByTestId('table-total');
  await expect(count).toHaveText('500 rows loaded');
  await expect(total).toHaveText('· ≈ 1,200 in total');
  await expect(view.getByText('keyset paging')).toBeVisible();
  await view.getByRole('button', { name: 'Count exactly' }).click();
  await expect(total).toHaveText('· 1,200 in total');

  const box = await view.getByTestId('data-grid-canvas').boundingBox();
  await page.mouse.move(box!.x + box!.width / 2, box!.y + box!.height / 2);
  await page.mouse.wheel(0, 500 * 26);
  await expect(count).toHaveText('1,000 rows loaded');
  await page.mouse.wheel(0, 500 * 26);
  await expect(count).toHaveText('1,200 rows loaded');
  await expect(view.getByText('more on scroll')).toHaveCount(0);
  await page.mouse.wheel(0, 500 * 26);
  await expect(cell(1, 1199)).toHaveText('event 1200');
});
