-- Querybara structure sync
-- Source: postgres app_dev
-- Target: postgres app_prod
-- Operations: 5

BEGIN;

-- Alter column public.i1.id
ALTER TABLE "public"."i1" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (START WITH 50 INCREMENT BY 5);

-- Alter column public.i2.id
ALTER TABLE "public"."i2" ALTER COLUMN "id" DROP IDENTITY;

-- Alter column public.i3.id
ALTER TABLE "public"."i3" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1;

-- Alter column public.i4.id
ALTER TABLE "public"."i4" ALTER COLUMN "id" DROP IDENTITY;

-- Create sequence public.i4_id_seq
CREATE SEQUENCE "public"."i4_id_seq" AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
ALTER SEQUENCE "public"."i4_id_seq" OWNED BY "public"."i4"."id";

-- Alter column public.i4.id (continued)
ALTER TABLE "public"."i4" ALTER COLUMN "id" SET DEFAULT nextval('public.i4_id_seq'::regclass);

COMMIT;
