create table i1 (id bigint generated always as identity (start with 50 increment by 5) primary key, v text);
create table i2 (id int primary key, v int);
create table i3 (id int generated by default as identity primary key);
create table i4 (id serial primary key, n int);
