create table i1 (id bigint primary key, v text);
create table i2 (id int generated always as identity primary key, v int);
create table i3 (id int generated always as identity (start with 10) primary key);
create table i4 (id int generated by default as identity primary key, n int);
insert into i1 values (1, 'a'), (70, 'b');
insert into i4 (n) values (1), (2);
