CREATE TABLE `events_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `message` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=500 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT COMMENT='old';
CREATE TABLE `archive` (
  `id` int NOT NULL,
  `year` smallint NOT NULL,
  PRIMARY KEY (`id`,`year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY RANGE (`year`)
(PARTITION p2022 VALUES LESS THAN (2023),
 PARTITION p2023 VALUES LESS THAN (2024),
 PARTITION pmax VALUES LESS THAN MAXVALUE);
CREATE TABLE `hashed` (
  `id` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY HASH (`id`) PARTITIONS 2;
