CREATE TABLE `t` (`id` int NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE DEFINER=`app`@`%` SQL SECURITY DEFINER VIEW `v_t` AS SELECT id FROM t;
CREATE DEFINER=`app`@`%` PROCEDURE `p_count`() SELECT COUNT(*) FROM t;
