-- Joinery structure sync
-- Source: postgres app_dev
-- Target: postgres app_prod
-- Operations: 4 (1 destructive)

BEGIN;

-- Create sequence public.s2_seq_seq
CREATE SEQUENCE "public"."s2_seq_seq" AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;

-- Alter column public.s1.id
--   info: The new identity continues after the highest existing value
ALTER TABLE "public"."s1" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."s1" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1);
SELECT setval(pg_get_serial_sequence('"public"."s1"', 'id'), coalesce(max("id"), 0) + 1, false) FROM "public"."s1";

-- Create column public.s2.seq
ALTER TABLE "public"."s2" ADD COLUMN "seq" integer DEFAULT nextval('public.s2_seq_seq'::regclass) NOT NULL;
ALTER SEQUENCE "public"."s2_seq_seq" OWNED BY "public"."s2"."seq";

-- Drop sequence public.s1_id_seq [destructive, not selected by default]
--   data-loss: Drops sequence public.s1_id_seq and its current value
DROP SEQUENCE IF EXISTS "public"."s1_id_seq";

COMMIT;
