-- Joinery structure sync
-- Source: postgres app_dev
-- Target: postgres app_prod
-- Operations: 8 (1 destructive)

BEGIN;

-- Create extension citext
CREATE EXTENSION IF NOT EXISTS "citext" WITH SCHEMA "public" VERSION '1.6';

-- Alter view public.eu_accounts
DROP VIEW "public"."eu_accounts";

-- Alter column public.accounts.email [destructive, not selected by default]
--   data-loss: changing text to public.citext can lose data or fail on existing values
ALTER TABLE "public"."accounts" ALTER COLUMN "email" TYPE public.citext USING "email"::public.citext;

-- Create table public.audit
CREATE TABLE "public"."audit" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "at" timestamp with time zone DEFAULT now()
) WITH (autovacuum_enabled=false, fillfactor=80);
CREATE INDEX audit_at ON public.audit USING btree (at DESC NULLS LAST);
COMMENT ON COLUMN "public"."audit"."at" IS 'when';
COMMENT ON INDEX "public"."audit_at" IS 'newest first';

-- Alter view public.eu_accounts (continued)
CREATE VIEW "public"."eu_accounts" AS
SELECT id,
    email,
    region
   FROM public.accounts
  WHERE (region = 'eu'::text)
WITH LOCAL CHECK OPTION;

-- Alter view public.secure_accounts
CREATE OR REPLACE VIEW "public"."secure_accounts" AS
SELECT id
   FROM public.accounts;

-- Create routine public.norm(text)
CREATE OR REPLACE FUNCTION public.norm(t text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$ select lower(trim(t)) $function$;

-- Create index public.accounts.accounts_norm_email [not selected by default]
CREATE INDEX accounts_norm_email ON public.accounts USING btree (public.norm((email)::text));

-- Create check public.accounts.accounts_region_check
--   may-fail: Adding the check fails if existing rows violate it
ALTER TABLE "public"."accounts" ADD CONSTRAINT "accounts_region_check" CHECK ((public.norm(region) <> ''::text));

COMMIT;
