CREATE TABLE r1 (id int NOT NULL, y int NOT NULL, PRIMARY KEY (id, y)) PARTITION BY RANGE (y) (PARTITION p1 VALUES LESS THAN (2000), PARTITION p2 VALUES LESS THAN (2010), PARTITION p3 VALUES LESS THAN (2020), PARTITION pmax VALUES LESS THAN MAXVALUE);
CREATE TABLE l1 (id int NOT NULL, region int NOT NULL, PRIMARY KEY (id, region)) PARTITION BY LIST (region) (PARTITION pa VALUES IN (1,2,3), PARTITION pb VALUES IN (4,5));
CREATE TABLE h1 (id int NOT NULL PRIMARY KEY) PARTITION BY HASH (id) PARTITIONS 4;
CREATE TABLE np (id int NOT NULL PRIMARY KEY);
CREATE TABLE addp (id int NOT NULL PRIMARY KEY) PARTITION BY KEY (id) PARTITIONS 3;
