CREATE TABLE r1 (id int NOT NULL, y int NOT NULL, PRIMARY KEY (id, y)) PARTITION BY RANGE (y) (PARTITION p1 VALUES LESS THAN (2000), PARTITION p3 VALUES LESS THAN (2020), PARTITION pmax VALUES LESS THAN MAXVALUE);
CREATE TABLE l1 (id int NOT NULL, region int NOT NULL, PRIMARY KEY (id, region)) PARTITION BY LIST (region) (PARTITION pa VALUES IN (1,2), PARTITION pc VALUES IN (9));
CREATE TABLE h1 (id int NOT NULL PRIMARY KEY) PARTITION BY HASH (id) PARTITIONS 2;
CREATE TABLE np (id int NOT NULL PRIMARY KEY) PARTITION BY HASH (id) PARTITIONS 2;
CREATE TABLE addp (id int NOT NULL PRIMARY KEY);
