CREATE TABLE t (id int NOT NULL PRIMARY KEY, a int, b bigint) DEFAULT CHARSET=utf8mb4;
CREATE VIEW v1 AS SELECT id, b FROM t;
CREATE VIEW v2 AS SELECT id, b * 2 AS b2 FROM v1;
CREATE VIEW v0 AS SELECT id FROM v2;
