CREATE TABLE t (id int NOT NULL PRIMARY KEY, a int, b int, c int) DEFAULT CHARSET=utf8mb4;
CREATE VIEW v1 AS SELECT id, a, c FROM t;
CREATE VIEW v2 AS SELECT id, c FROM v1;
CREATE VIEW v3 AS SELECT id FROM v2;
