CREATE TABLE a (id int NOT NULL PRIMARY KEY, t varchar(20), u varchar(20) CHARACTER SET latin1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='new';
CREATE TABLE b (id int NOT NULL PRIMARY KEY, t text) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE m (id int NOT NULL PRIMARY KEY) ENGINE=MyISAM;
