CREATE TABLE a (id int NOT NULL PRIMARY KEY, t varchar(20), u varchar(20)) ENGINE=MyISAM DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;
CREATE TABLE b (id int NOT NULL PRIMARY KEY, t text) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE m (id int NOT NULL PRIMARY KEY) ENGINE=InnoDB;
