import type { CellValue, Session } from '@querybara/core';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import {
  planDbTransfer,
  runDbTransfer,
  type DbTransferSpec,
  type DbTransferSummary,
} from '../../src';
import { opener, scratch, server, type Scratch } from './db-helpers';
import { query, type TestServer } from './helpers';

/**
 * SQL → SQL transfers against the real servers (spec §12): PostgreSQL into MySQL and MariaDB
 * and back, with the types that go wrong — decimals, big integers, dates and time zones,
 * binary, JSON, arrays, unicode, NULLs and large text — plus keys, indexes and foreign keys
 * created after the data, sequences reset, and the table modes.
 */

const PG = server('postgres');
const MYSQL = server('mysql');
const MARIADB = server('mariadb');

const LARGE = 'large text ✓ '.repeat(20_000);

const PG_SOURCE = [
  `CREATE TABLE people (
    id serial PRIMARY KEY,
    name varchar(50) NOT NULL,
    price numeric(12,4),
    big bigint,
    ratio double precision,
    ok boolean DEFAULT true,
    born date,
    seen timestamp(6) with time zone,
    at timestamp(3) without time zone,
    clock time(0) without time zone,
    doc jsonb,
    bin bytea,
    ref uuid,
    tags integer[],
    note text,
    CONSTRAINT people_name_key UNIQUE (name)
  )`,
  `CREATE INDEX people_born_idx ON people (born)`,
  `CREATE TABLE orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id integer NOT NULL REFERENCES people (id),
    total numeric(10,2) NOT NULL DEFAULT 0,
    placed timestamp with time zone DEFAULT now(),
    status varchar(20) DEFAULT 'new'
  )`,
  `INSERT INTO people (id, name, price, big, ratio, ok, born, seen, at, clock, doc, bin, ref, tags, note) VALUES
    (1, 'Ada Lovelace', 12.3456, 9007199254740993, 0.1, true, '1815-12-10', '2024-01-02 03:04:05.123456+00', '2024-01-02 03:04:05.123', '10:11:12', '{"a": [1, 2], "b": {"c": null}}', '\\xdeadbeef00ff', '0b5e4b9c-6f1e-4c8e-9d7a-2a1c3e4f5a6b', '{1,2,3}', '${LARGE}'),
    (2, 'Grüße 東京 😀', -0.0001, -9223372036854775808, 1e-300, false, '1999-12-31', '1999-12-31 23:59:59+05:30', '1999-12-31 23:59:59', '00:00:00', '[]', '\\x', 'ffffffff-ffff-ffff-ffff-ffffffffffff', '{}', ''),
    (10, 'Nulls', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)`,
  `SELECT setval('people_id_seq', 10)`,
  `INSERT INTO orders (person_id, total, status) VALUES (1, 10.50, 'paid'), (1, 0, 'new'), (10, 99.99, 'O''Brien "quoted"')`,
];

async function rows(session: Session, sql: string): Promise<CellValue[][]> {
  return query(session, sql);
}

function spec(
  objects: DbTransferSpec['objects'],
  options: DbTransferSpec['options'] = {},
): DbTransferSpec {
  return { source: {}, target: {}, objects, options };
}

async function transfer(
  from: Scratch,
  to: Scratch,
  transferSpec: DbTransferSpec,
): Promise<DbTransferSummary> {
  return runDbTransfer({
    spec: transferSpec,
    source: opener(() => from.connect()),
    target: opener(() => to.connect()),
  });
}

function json(value: CellValue | undefined): unknown {
  return typeof value === 'string' ? JSON.parse(value) : value;
}

describe.skipIf(!PG || (!MYSQL && !MARIADB))('PostgreSQL → MySQL / MariaDB and back', () => {
  const targets = [MYSQL, MARIADB].filter((s): s is TestServer => s !== undefined);
  let source: Scratch;
  const made: Scratch[] = [];

  beforeAll(async () => {
    source = await scratch(PG!, 'pg_src');
    made.push(source);
    const session = await source.connect();
    try {
      for (const statement of PG_SOURCE) await query(session, statement);
    } finally {
      await session.close();
    }
  });

  afterAll(async () => {
    for (const db of made) await db.drop().catch(() => undefined);
  });

  for (const target of targets) {
    describe(`into ${target.engine}`, () => {
      let into: Scratch;
      let back: Scratch;
      let session: Session;

      beforeAll(async () => {
        into = await scratch(target, `pg_to_${target.engine}`);
        made.push(into);
        session = await into.connect();
      });
      afterAll(async () => {
        await session?.close();
      });

      it('plans the tables with the type mapping and the deferred keys', async () => {
        const src = await source.connect();
        try {
          const plan = await planDbTransfer({
            spec: spec([{ name: 'people' }, { name: 'orders' }]),
            source: src,
            target: session,
          });
          expect(plan.problems).toEqual([]);
          const people = plan.tables.find((t) => t.source === 'people')!;
          const types = Object.fromEntries(people.columns.map((c) => [c.source, c.targetType]));
          expect(types).toMatchObject({
            id: 'int',
            name: 'varchar(50)',
            price: 'decimal(12,4)',
            ok: 'tinyint(1)',
            seen: 'datetime(6)',
            doc: 'json',
            bin: 'longblob',
            tags: 'json',
            note: 'longtext',
          });
          expect(types['ref']).toMatch(/^(char\(36\)|uuid)$/);
          expect(plan.creates).toEqual(['Create table people', 'Create table orders']);
          expect(plan.after.some((s) => /FOREIGN KEY/.test(s))).toBe(true);
          expect(plan.after.some((s) => /ADD UNIQUE KEY/.test(s))).toBe(true);
        } finally {
          await src.close();
        }
      });

      it('copies every value, then adds keys, indexes and foreign keys and resets counters', async () => {
        const summary = await transfer(
          source,
          into,
          spec([{ name: 'people' }, { name: 'orders' }]),
        );
        expect(summary.errors).toEqual([]);
        expect(summary.status).toBe('completed');
        expect(summary.rowsWritten).toBe(6);
        const people = await rows(
          session,
          'SELECT id, name, price, big, ratio, ok, born, seen, at, clock, doc, bin, ref, tags, note FROM people ORDER BY id',
        );
        expect(people).toHaveLength(3);
        const [ada, grusse, nulls] = people as [CellValue[], CellValue[], CellValue[]];
        expect(ada.slice(0, 10)).toEqual([
          1,
          'Ada Lovelace',
          '12.3456',
          9007199254740993n,
          0.1,
          1,
          '1815-12-10',
          '2024-01-02 03:04:05.123456',
          '2024-01-02 03:04:05.123',
          '10:11:12',
        ]);
        expect(json(ada[10])).toEqual({ a: [1, 2], b: { c: null } });
        expect(ada[11]).toEqual(Uint8Array.from([0xde, 0xad, 0xbe, 0xef, 0x00, 0xff]));
        expect(ada[12]).toBe('0b5e4b9c-6f1e-4c8e-9d7a-2a1c3e4f5a6b');
        expect(json(ada[13])).toEqual([1, 2, 3]);
        expect(ada[14]).toBe(LARGE);
        expect(grusse.slice(0, 8)).toEqual([
          2,
          'Grüße 東京 😀',
          '-0.0001',
          -9223372036854775808n,
          1e-300,
          0,
          '1999-12-31',
          // 23:59:59+05:30 is 18:29:59 UTC.
          '1999-12-31 18:29:59.000000',
        ]);
        expect(json(grusse[10])).toEqual([]);
        expect(grusse[11]).toEqual(new Uint8Array());
        expect(json(grusse[13])).toEqual([]);
        expect(grusse[14]).toBe('');
        expect(nulls.slice(2)).toEqual(new Array(13).fill(null));

        // The counter moved past the copied ids, the unique key and the foreign key exist.
        await query(session, "INSERT INTO people (name) VALUES ('Next')");
        expect(await rows(session, "SELECT id FROM people WHERE name = 'Next'")).toEqual([[11]]);
        await expect(query(session, "INSERT INTO people (name) VALUES ('Next')")).rejects.toThrow(
          /Duplicate/,
        );
        await expect(
          query(session, 'INSERT INTO orders (person_id, total) VALUES (999, 1)'),
        ).rejects.toThrow(/foreign key/i);
        const indexes = await rows(
          session,
          "SELECT INDEX_NAME FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'people' ORDER BY 1",
        );
        expect(indexes.flat()).toEqual(
          expect.arrayContaining(['PRIMARY', 'people_born_idx', 'people_name_key']),
        );
        const orders = await rows(
          session,
          'SELECT id, person_id, total, status FROM orders ORDER BY id',
        );
        expect(orders).toEqual([
          [1, 1, '10.50', 'paid'],
          [2, 1, '0.00', 'new'],
          [3, 10, '99.99', 'O\'Brien "quoted"'],
        ]);
      });

      it('comes back to PostgreSQL with the values intact', async () => {
        back = await scratch(PG!, `${target.engine}_to_pg`);
        made.push(back);
        const summary = await transfer(into, back, spec([{ name: 'people' }, { name: 'orders' }]));
        expect(summary.errors).toEqual([]);
        expect(summary.status).toBe('completed');
        const pg = await back.connect();
        try {
          const people = await rows(
            pg,
            'SELECT id, name, price::text, big, ok, born::text, bin, doc::text, note, seen::text FROM people ORDER BY id',
          );
          expect(people[0]).toEqual([
            1,
            'Ada Lovelace',
            '12.3456',
            9007199254740993n,
            true,
            '1815-12-10',
            Uint8Array.from([0xde, 0xad, 0xbe, 0xef, 0x00, 0xff]),
            '{"a": [1, 2], "b": {"c": null}}',
            LARGE,
            '2024-01-02 03:04:05.123456',
          ]);
          expect(people[1]?.slice(0, 5)).toEqual([
            2,
            'Grüße 東京 😀',
            '-0.0001',
            -9223372036854775808n,
            false,
          ]);
          expect(people[2]?.slice(2)).toEqual(new Array(8).fill(null));
          // The next id follows the data.
          await query(pg, "INSERT INTO people (name) VALUES ('Again')");
          expect(await rows(pg, "SELECT id FROM people WHERE name = 'Again'")).toEqual([[12]]);
        } finally {
          await pg.close();
        }
      });

      it('refuses create when the table exists, and truncates or appends when asked', async () => {
        const src = await source.connect();
        try {
          const plan = await planDbTransfer({
            spec: spec([{ name: 'orders' }]),
            source: src,
            target: session,
          });
          expect(plan.problems[0]).toMatch(/already exists/);
        } finally {
          await src.close();
        }
        const truncated = await transfer(
          source,
          into,
          spec([{ name: 'orders' }], { mode: 'truncate' }),
        );
        expect(truncated.status).toBe('completed');
        expect(await rows(session, 'SELECT COUNT(*) FROM orders')).toEqual([[3]]);
        const appended = await transfer(
          source,
          into,
          spec([{ name: 'orders', columns: [{ source: 'id', skip: true }] }], { mode: 'append' }),
        );
        expect(appended.status).toBe('completed');
        expect(await rows(session, 'SELECT COUNT(*), MAX(id) FROM orders')).toEqual([[6, 6]]);
      });

      it('drops and creates again, with a column renamed, skipped and retyped', async () => {
        const summary = await transfer(
          source,
          into,
          spec(
            [
              {
                name: 'people',
                target: 'persons',
                columns: [
                  { source: 'name', target: 'full_name', dataType: 'varchar(200)' },
                  { source: 'note', skip: true },
                ],
              },
            ],
            { mode: 'drop-create', parallel: 1 },
          ),
        );
        expect(summary.status).toBe('completed');
        const columns = await rows(
          session,
          "SELECT COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'persons' ORDER BY ORDINAL_POSITION",
        );
        expect(columns.map((c) => c[0])).not.toContain('note');
        expect(columns).toContainEqual(['full_name', 'varchar(200)']);
        const again = await transfer(
          source,
          into,
          spec([{ name: 'people', target: 'persons' }], { mode: 'drop-create' }),
        );
        expect(again.status).toBe('completed');
        expect(await rows(session, 'SELECT COUNT(*) FROM persons')).toEqual([[3]]);
      });
    });
  }
});

const MYSQL_SOURCE = (engine: 'mysql' | 'mariadb'): string[] => [
  `SET SESSION sql_mode = ''`,
  `CREATE TABLE items (
    id int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
    flag tinyint(1) NOT NULL DEFAULT 1,
    bit1 bit(1),
    small smallint unsigned,
    huge bigint unsigned,
    amount decimal(20,6),
    ratio double,
    day date,
    moment datetime(6),
    stamp timestamp(3) NULL,
    clock time,
    label varchar(100) CHARACTER SET utf8mb4,
    body mediumtext,
    doc json,
    raw varbinary(64),
    blobv longblob,
    ref char(36),
    choice enum('red','green','blue'),
    yr year,
    KEY items_day (day)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `INSERT INTO items VALUES
    (1, 1, b'1', 65535, 18446744073709551615, 12345678901234.123456, 0.5, '2024-02-29', '2024-01-02 03:04:05.123456', '2024-01-02 03:04:05.500', '-12:00:00', 'Grüße 😀', '${'y'.repeat(70_000)}', '{"k": "v", "n": [1, 2.5]}', X'00ff', X'deadbeef', '0b5e4b9c-6f1e-4c8e-9d7a-2a1c3e4f5a6b', 'green', 2024),
    (2, 0, b'0', 0, 0, -0.000001, -1.5e10, '0000-00-00', '0000-00-00 00:00:00', NULL, '23:59:59', '', '', '[]', X'', X'', '', 'red', 1901),
    (7, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)`,
  ...(engine === 'mysql' ? [] : []),
];

describe.skipIf(!PG || (!MYSQL && !MARIADB))('MySQL / MariaDB → PostgreSQL', () => {
  const sources = [MYSQL, MARIADB].filter((s): s is TestServer => s !== undefined);
  const made: Scratch[] = [];
  afterAll(async () => {
    for (const db of made) await db.drop().catch(() => undefined);
  });

  for (const origin of sources) {
    it(`copies ${origin.engine} types into PostgreSQL, zero dates as NULL`, async () => {
      const from = await scratch(origin, `${origin.engine}_src`);
      made.push(from);
      const to = await scratch(PG!, `from_${origin.engine}`);
      made.push(to);
      const src = await from.connect();
      try {
        for (const statement of MYSQL_SOURCE(origin.engine as 'mysql' | 'mariadb'))
          await query(src, statement);
      } finally {
        await src.close();
      }
      const summary = await transfer(
        from,
        to,
        spec([{ name: 'items', columns: [{ source: 'clock', dataType: 'interval' }] }], {
          onError: 'skip',
        }),
      );
      expect(summary.errors).toEqual([]);
      expect(summary.status).toBe('completed');
      const pg = await to.connect();
      try {
        const types = await rows(
          pg,
          "SELECT column_name, format_type(atttypid, atttypmod) FROM information_schema.columns c JOIN pg_attribute a ON a.attname = c.column_name AND a.attrelid = 'public.items'::regclass WHERE table_name = 'items' ORDER BY ordinal_position",
        );
        expect(Object.fromEntries(types)).toMatchObject({
          id: 'bigint',
          flag: 'boolean',
          bit1: 'boolean',
          small: 'integer',
          huge: 'numeric(20,0)',
          amount: 'numeric(20,6)',
          day: 'date',
          moment: 'timestamp(6) without time zone',
          stamp: 'timestamp(3) with time zone',
          clock: 'interval',
          doc: 'jsonb',
          raw: 'bytea',
          choice: 'character varying(5)',
          yr: 'smallint',
        });
        const items = await rows(
          pg,
          'SELECT id, flag, bit1, small, huge::text, amount::text, ratio, day::text, moment::text, stamp::text, clock::text, label, length(body), doc::text, raw, blobv, ref, choice, yr FROM items ORDER BY id',
        );
        expect(items[0]).toEqual([
          1,
          true,
          true,
          65535,
          '18446744073709551615',
          '12345678901234.123456',
          0.5,
          '2024-02-29',
          '2024-01-02 03:04:05.123456',
          '2024-01-02 03:04:05.5+00',
          '-12:00:00',
          'Grüße 😀',
          70_000,
          '{"k": "v", "n": [1, 2.5]}',
          Uint8Array.from([0, 255]),
          Uint8Array.from([0xde, 0xad, 0xbe, 0xef]),
          '0b5e4b9c-6f1e-4c8e-9d7a-2a1c3e4f5a6b',
          'green',
          2024,
        ]);
        // MySQL's zero dates have no PostgreSQL value.
        expect(items[1]?.slice(7, 9)).toEqual([null, null]);
        expect(items[2]?.slice(2)).toEqual(new Array(17).fill(null));
        await query(pg, 'INSERT INTO items (flag) VALUES (true)');
        expect(await rows(pg, 'SELECT max(id) FROM items')).toEqual([[8]]);
      } finally {
        await pg.close();
      }
    });
  }

  it.skipIf(!MYSQL || !MARIADB)(
    'moves a table between MySQL and MariaDB with JSON kept',
    async () => {
      const from = await scratch(MYSQL!, 'my_to_maria');
      made.push(from);
      const to = await scratch(MARIADB!, 'maria_from_my');
      made.push(to);
      const src = await from.connect();
      try {
        for (const statement of MYSQL_SOURCE('mysql')) await query(src, statement);
      } finally {
        await src.close();
      }
      const summary = await transfer(from, to, spec([{ name: 'items' }]));
      expect(summary.errors).toEqual([]);
      const maria = await to.connect();
      try {
        expect(
          await rows(maria, "SELECT JSON_VALUE(doc, '$.k'), day, choice FROM items ORDER BY id"),
        ).toEqual([
          ['v', '2024-02-29', 'green'],
          [null, '0000-00-00', 'red'],
          [null, null, null],
        ]);
      } finally {
        await maria.close();
      }
    },
  );
});
