CREATE TABLE acc (id int NOT NULL PRIMARY KEY, bal decimal(10,2) NOT NULL DEFAULT 0, owner varchar(40)) DEFAULT CHARSET=utf8mb4;
CREATE TABLE log (id int NOT NULL AUTO_INCREMENT PRIMARY KEY, msg text) DEFAULT CHARSET=utf8mb4;
CREATE FUNCTION fee(x decimal(10,2)) RETURNS decimal(10,2) DETERMINISTIC COMMENT 'fee ''calc''' RETURN x * 0.02;
CREATE VIEW v_acc AS SELECT id, bal FROM acc WHERE bal > 0 WITH CASCADED CHECK OPTION;
CREATE VIEW v_fee AS SELECT id, fee(bal) AS f FROM acc;
CREATE VIEW v_rich AS SELECT id FROM v_acc WHERE bal > 1000;
CREATE SQL SECURITY INVOKER VIEW v_owner AS SELECT owner, 'it''s' AS lit, COUNT(*) AS n FROM acc GROUP BY owner;
DELIMITER //
CREATE PROCEDURE audit_all(IN p_note varchar(100), OUT p_n int)
  MODIFIES SQL DATA
  COMMENT 'audits'
BEGIN
  DECLARE done int DEFAULT 0;
  INSERT INTO log (msg) VALUES (CONCAT('audit; ', p_note));
  SELECT COUNT(*) INTO p_n FROM acc;
END//
CREATE TRIGGER acc_ai AFTER INSERT ON acc FOR EACH ROW
BEGIN
  INSERT INTO log (msg) VALUES (CONCAT('new ', NEW.id, ';'));
END//
CREATE TRIGGER acc_bu BEFORE UPDATE ON acc FOR EACH ROW
SET NEW.bal = GREATEST(NEW.bal, 0)//
DELIMITER ;
CREATE EVENT ev1 ON SCHEDULE EVERY 2 HOUR STARTS '2030-01-01 00:00:00' ON COMPLETION PRESERVE DISABLE COMMENT 'ev' DO DELETE FROM log WHERE id < 0;
