create sequence s1 as integer start 10 increment 5 minvalue 5 maxvalue 1000000 cache 20 cycle;
create sequence s2 as bigint increment -1 start -1 minvalue -1000 maxvalue -1;
create sequence s4 maxvalue 2;
create sequence s5 minvalue 200 maxvalue 300 start 250;
create table t (id bigserial primary key, n int default nextval('s1'), code int generated by default as identity (start with 100 increment by 10 maxvalue 100000));
create sequence owned_later;
alter sequence owned_later owned by t.n;
