create sequence s1 start 1;
create sequence s3;
create sequence s4;
select nextval('s4'), nextval('s4'), nextval('s4');
create sequence s5 minvalue 1 maxvalue 100 start 1;
create table t (id serial primary key, n int, code int generated by default as identity);
create sequence owned_later;
