CREATE TABLE declared_compact (id int NOT NULL PRIMARY KEY, note varchar(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT;
CREATE TABLE declared_default (id int NOT NULL PRIMARY KEY, note varchar(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE same_dynamic (id int NOT NULL PRIMARY KEY, note varchar(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE same_default (id int NOT NULL PRIMARY KEY, note varchar(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DEFAULT;
