create table items (
  id int not null,
  code text collate "C",
  qty int default 1,
  price numeric,
  total numeric,
  tag text,
  gen_old int generated always as (id + 1) stored,
  seq_id int generated by default as identity
) with (fillfactor = 90);
comment on column items.tag is 'old comment';
comment on table items is 'will go';
