import type { SchemaSnapshot } from '@querybara/core';
import { describe, expect, it } from 'vitest';

import {
  EditError,
  addColumn,
  addRelation,
  addTable,
  dropColumn,
  dropRelation,
  dropTable,
  findTable,
  modelChanges,
  moveColumn,
  renameRules,
  renameTable,
  setTableComment,
  singular,
  startModel,
  togglePrimaryKey,
  toggleUnique,
  updateColumn,
  updateRelation,
  type EditContext,
  type ModelState,
} from '../src/renderer/src/state/er-diagram/edit';
import { modelScript, validateModel } from '../src/renderer/src/state/er-diagram/forward';
import { shop, shopMysql } from './er-fixtures';

const PG: EditContext = { engine: 'postgres', schema: 'public' };
const MY: EditContext = { engine: 'mysql', schema: 'shop' };

/** A database whose `public` schema is empty: a new design. */
function empty(): SchemaSnapshot {
  const snapshot = shop();
  return {
    ...snapshot,
    schemas: snapshot.schemas.map((s) =>
      s.name === 'public' ? { ...s, tables: [], views: [] } : s,
    ),
  };
}

function script(state: ModelState, base: SchemaSnapshot, context = PG): string {
  return modelScript(state, base, context).statements.join(';\n');
}

describe('an ER model', () => {
  it('starts from the live schema, every table and column its own origin', () => {
    const state = startModel(shop(), PG);
    expect(state.tableOrigins).toEqual({
      customers: 'customers',
      orders: 'orders',
      customer_profiles: 'customer_profiles',
      employees: 'employees',
    });
    expect(state.columnOrigins['orders']).toEqual({
      id: 'id',
      customer_id: 'customer_id',
      total: 'total',
      note: 'note',
    });
    expect(modelScript(state, shop(), PG).statements).toEqual([]);
    expect(modelChanges(state, shop(), PG).count).toBe(0);
  });

  it('adds tables with a surrogate key, named new_table, new_table_2…', () => {
    let state = startModel(empty(), PG);
    const first = addTable(state, PG);
    expect(first.name).toBe('new_table');
    state = addTable(first.state, PG).state;
    expect(findTable(state, PG, 'new_table_2').primaryKey).toEqual({
      name: 'new_table_2_pkey',
      columns: ['id'],
    });
    expect(() => addTable(state, PG, 'NEW_TABLE_2')).not.toThrow();
    expect(() => addTable(state, PG, 'new_table')).toThrow(EditError);
    expect(() => addTable(state, PG, '  ')).toThrow('A table needs a name');
    expect(() => addTable(state, PG, 'x'.repeat(64))).toThrow('63 characters');
    expect(script(state, empty())).toContain(
      'CREATE TABLE "public"."new_table" (\n  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL',
    );
  });

  it('designs a new schema into CREATE TABLE statements in dependency order', () => {
    let state = startModel(empty(), PG);
    state = addTable(state, PG, 'orders').state;
    state = addTable(state, PG, 'customers').state;
    state = addColumn(state, PG, 'customers', {
      name: 'email',
      dataType: 'text',
      nullable: false,
    }).state;
    state = toggleUnique(state, PG, 'customers', 'email');
    const related = addRelation(state, PG, {
      child: 'orders',
      parent: 'customers',
      onDelete: 'CASCADE',
    });
    expect(related.added).toEqual(['customer_id']);
    expect(related.name).toBe('orders_customer_id_fkey');
    state = related.state;
    // A new table's referencing column is required.
    expect(findTable(state, PG, 'orders').columns[1]).toMatchObject({
      name: 'customer_id',
      dataType: 'bigint',
      nullable: false,
    });
    expect(findTable(state, PG, 'orders').columns[1]!.identity).toBeUndefined();
    const text = script(state, empty());
    // Tables first, then the foreign key between them.
    expect(modelScript(state, empty(), PG).statements).toEqual([
      'BEGIN',
      expect.stringMatching(/^CREATE TABLE "public"."orders"/),
      expect.stringMatching(
        /^CREATE TABLE "public"."customers"[^]*CONSTRAINT "customers_email_key" UNIQUE \("email"\)/,
      ),
      'ALTER TABLE "public"."orders" ADD CONSTRAINT "orders_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers" ("id") ON DELETE CASCADE',
      'COMMIT',
    ]);
    expect(modelScript(state, empty(), PG).transactional).toBe(true);
    // The new table has no rows a foreign key could fail on.
    expect(modelScript(state, empty(), PG).warnings).toEqual([]);
    expect(text).toContain('"customer_id" bigint NOT NULL');
    expect(modelChanges(state, empty(), PG)).toMatchObject({ count: 2, dropped: [] });
    expect(validateModel(state, empty(), PG)).toEqual([]);
  });

  it('renames tables as renames, with the foreign keys that point at them', () => {
    let state = startModel(shop(), PG);
    state = renameTable(state, PG, 'customers', 'clients');
    expect(findTable(state, PG, 'orders').foreignKeys[0]!.refTable).toBe('clients');
    expect(state.tableOrigins['clients']).toBe('customers');
    expect(renameRules(state, PG)).toEqual([
      { objectKind: 'table', schema: 'public', from: 'customers', to: 'clients' },
    ]);
    const result = modelScript(state, shop(), PG);
    expect(result.statements).toEqual([
      'BEGIN',
      'ALTER TABLE "public"."customers" RENAME TO "clients"',
      'COMMIT',
    ]);
    expect(result.statements.join('\n')).not.toMatch(/DROP TABLE|CREATE TABLE/);
    expect(result.destructive).toEqual([]);
    expect(() => renameTable(state, PG, 'clients', 'orders')).toThrow('already a table');
    expect(modelChanges(state, shop(), PG).tables.get('clients')).toBe('changed');
  });

  it('follows a table and its columns into the foreign keys of other schemas', () => {
    let state = renameTable(startModel(shop(), PG), PG, 'orders', 'purchases');
    state = updateColumn(state, PG, 'purchases', 'id', { name: 'purchase_id' });
    const invoices = state.snapshot.schemas.find((s) => s.name === 'sales')!.tables[0]!;
    expect(invoices.foreignKeys[0]).toMatchObject({
      refSchema: 'public',
      refTable: 'purchases',
      refColumns: ['purchase_id'],
    });
    expect(modelScript(state, shop(), PG).statements).toEqual([
      'BEGIN',
      'ALTER TABLE "public"."orders" RENAME TO "purchases"',
      'ALTER TABLE "public"."purchases" RENAME COLUMN "id" TO "purchase_id"',
      'COMMIT',
    ]);
    expect(() => togglePrimaryKey(state, PG, 'purchases', 'purchase_id')).toThrow('references');
    const dropped = dropTable(state, PG, 'purchases');
    expect(
      dropped.snapshot.schemas.find((s) => s.name === 'sales')!.tables[0]!.foreignKeys,
    ).toEqual([]);
    expect(script(dropped, shop())).toContain(
      'ALTER TABLE "sales"."invoices" DROP CONSTRAINT "invoices_order_id_fkey"',
    );
  });

  it('drops a table and the foreign keys that reference it, flagged as destructive', () => {
    const state = dropTable(startModel(shop(), PG), PG, 'customers');
    expect(findTable(state, PG, 'orders').foreignKeys).toEqual([]);
    const result = modelScript(state, shop(), PG);
    // The foreign keys go before the table.
    expect(result.statements).toEqual([
      'BEGIN',
      'ALTER TABLE "public"."orders" DROP CONSTRAINT "orders_customer_id_fkey"',
      'ALTER TABLE "public"."customer_profiles" DROP CONSTRAINT "customer_profiles_customer_id_fkey"',
      'DROP TABLE "public"."customers"',
      'COMMIT',
    ]);
    expect(result.destructive.map((op) => op.qualifiedName)).toContain('public.customers');
    expect(modelChanges(state, shop(), PG).dropped).toEqual(['customers']);
  });

  it('adds, renames, retypes and drops columns', () => {
    let state = startModel(shop(), PG);
    const added = addColumn(state, PG, 'orders', {
      name: 'placed_at',
      dataType: 'timestamp with time zone',
    });
    state = added.state;
    expect(() => addColumn(state, PG, 'orders', { name: 'PLACED_AT' })).not.toThrow();
    expect(() => addColumn(state, PG, 'orders', { name: 'placed_at' })).toThrow('already has');
    state = updateColumn(state, PG, 'orders', 'note', {
      name: 'remarks',
      dataType: 'varchar(500)',
    });
    state = updateColumn(state, PG, 'orders', 'total', { default: ' 0 ', comment: 'Incl. VAT' });
    const text = script(state, shop());
    expect(findTable(state, PG, 'orders').columns.find((c) => c.name === 'remarks')!.dataType).toBe(
      'character varying(500)',
    );
    expect(text).toContain('ALTER TABLE "public"."orders" RENAME COLUMN "note" TO "remarks"');
    expect(text).toContain('ALTER COLUMN "remarks" TYPE character varying(500)');
    expect(text).toContain('ADD COLUMN "placed_at" timestamp with time zone');
    expect(text).toContain('ALTER COLUMN "total" SET DEFAULT 0');
    expect(text).toContain(`COMMENT ON COLUMN "public"."orders"."total" IS 'Incl. VAT'`);
    expect(modelChanges(state, shop(), PG).columns.get('orders')).toEqual(
      new Map([
        ['total', 'changed'],
        ['remarks', 'changed'],
        ['placed_at', 'new'],
      ]),
    );

    const dropped = dropColumn(state, PG, 'orders', 'customer_id');
    expect(findTable(dropped, PG, 'orders').foreignKeys).toEqual([]);
    expect(findTable(dropped, PG, 'orders').columns.map((c) => c.ordinal)).toEqual([1, 2, 3, 4]);
    expect(script(dropped, shop())).toContain('DROP COLUMN "customer_id"');
  });

  it('follows a renamed column into keys and the foreign keys that reference it', () => {
    let state = startModel(shop(), PG);
    state = updateColumn(state, PG, 'customers', 'id', { name: 'customer_no' });
    expect(findTable(state, PG, 'customers').primaryKey!.columns).toEqual(['customer_no']);
    expect(findTable(state, PG, 'orders').foreignKeys[0]!.refColumns).toEqual(['customer_no']);
    expect(findTable(state, PG, 'customer_profiles').foreignKeys[0]!.refColumns).toEqual([
      'customer_no',
    ]);
    const text = script(state, shop());
    expect(modelScript(state, shop(), PG).statements).toEqual([
      'BEGIN',
      'ALTER TABLE "public"."customers" RENAME COLUMN "id" TO "customer_no"',
      'COMMIT',
    ]);
    expect(text).not.toContain('DROP CONSTRAINT');

    // A self-reference follows both ends.
    state = updateColumn(startModel(shop(), PG), PG, 'employees', 'id', { name: 'employee_id' });
    expect(findTable(state, PG, 'employees').foreignKeys[0]).toMatchObject({
      columns: ['manager_id'],
      refColumns: ['employee_id'],
    });
  });

  it('keeps key columns NOT NULL, and a table at least one column', () => {
    const state = startModel(shop(), PG);
    expect(() => updateColumn(state, PG, 'orders', 'id', { nullable: true })).toThrow(
      'primary key column cannot allow NULL',
    );
    expect(() => updateColumn(state, PG, 'orders', 'id', { dataType: ' ' })).toThrow(
      'needs a type',
    );
    const one = addTable(startModel(empty(), PG), PG, 'solo').state;
    expect(() => dropColumn(one, PG, 'solo', 'id')).toThrow('at least one column');
  });

  it('moves columns', () => {
    let state = startModel(shopMysql(), MY);
    state = moveColumn(state, MY, 'orders', 'total', 0);
    expect(findTable(state, MY, 'orders').columns.map((c) => `${c.ordinal}:${c.name}`)).toEqual([
      '1:total',
      '2:id',
      '3:customer_id',
    ]);
    expect(script(state, shopMysql(), MY)).toContain(
      'ALTER TABLE `orders` MODIFY COLUMN `total` decimal(10,2) NOT NULL FIRST',
    );
    expect(modelScript(state, shopMysql(), MY).transactional).toBe(false);
    expect(moveColumn(state, MY, 'orders', 'total', -5)).toBe(state);
  });

  it('sets primary and unique keys', () => {
    let state = addTable(startModel(empty(), PG), PG, 'tags').state;
    state = addColumn(state, PG, 'tags', { name: 'label', dataType: 'text' }).state;
    state = togglePrimaryKey(state, PG, 'tags', 'label');
    expect(findTable(state, PG, 'tags').primaryKey!.columns).toEqual(['id', 'label']);
    expect(findTable(state, PG, 'tags').columns[1]!.nullable).toBe(false);
    state = togglePrimaryKey(state, PG, 'tags', 'id');
    state = togglePrimaryKey(state, PG, 'tags', 'label');
    expect(findTable(state, PG, 'tags').primaryKey).toBeUndefined();

    state = toggleUnique(state, PG, 'tags', 'label');
    expect(findTable(state, PG, 'tags').uniques).toEqual([
      { name: 'tags_label_key', columns: ['label'] },
    ]);
    state = toggleUnique(state, PG, 'tags', 'label');
    expect(findTable(state, PG, 'tags').uniques).toEqual([]);

    // A key column a foreign key references stays in the key.
    expect(() => togglePrimaryKey(startModel(shop(), PG), PG, 'customers', 'id')).toThrow(
      'references customers.id',
    );
  });

  it('adds relationships to a key, with new columns nullable on live tables', () => {
    let state = startModel(shop(), PG);
    const added = addRelation(state, PG, { child: 'employees', parent: 'customers' });
    expect(added.added).toEqual(['customer_id']);
    state = added.state;
    expect(findTable(state, PG, 'employees').columns.at(-1)).toMatchObject({
      name: 'customer_id',
      dataType: 'integer',
      nullable: true,
    });
    expect(modelScript(state, shop(), PG).statements).toEqual([
      'BEGIN',
      'ALTER TABLE "public"."employees" ADD COLUMN "customer_id" integer',
      'ALTER TABLE "public"."employees" ADD CONSTRAINT "employees_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers" ("id")',
      'COMMIT',
    ]);

    // To chosen columns, which must be a key of the parent.
    expect(() =>
      addRelation(state, PG, {
        child: 'orders',
        childColumns: ['note'],
        parent: 'customers',
        parentColumns: ['name'],
      }),
    ).toThrow('not a primary or unique key');
    expect(() =>
      addRelation(state, PG, {
        child: 'orders',
        childColumns: ['customer_id'],
        parent: 'customers',
      }),
    ).toThrow('already references customers');
    const byEmail = addRelation(state, PG, {
      child: 'orders',
      childColumns: ['note'],
      parent: 'customers',
      parentColumns: ['email'],
    });
    expect(byEmail.added).toEqual([]);
    expect(byEmail.name).toBe('orders_note_fkey');

    state = updateRelation(byEmail.state, PG, 'orders', 'orders_note_fkey', {
      onDelete: 'SET NULL',
    });
    expect(script(state, shop())).toContain('ON DELETE SET NULL');
    state = dropRelation(state, PG, 'orders', 'orders_note_fkey');
    expect(script(state, shop())).not.toContain('orders_note_fkey');
  });

  it('refuses a relationship to a table without a key', () => {
    let state = addTable(startModel(empty(), PG), PG, 'loose').state;
    state = togglePrimaryKey(state, PG, 'loose', 'id');
    state = addTable(state, PG, 'child').state;
    expect(() => addRelation(state, PG, { child: 'child', parent: 'loose' })).toThrow(
      'loose has no primary or unique key',
    );
  });

  it('writes MySQL: AUTO_INCREMENT keys, renames and foreign keys', () => {
    let state = startModel(shopMysql(), MY);
    const created = addTable(state, MY, 'invoices');
    expect(findTable(created.state, MY, 'invoices')).toMatchObject({
      primaryKey: { name: 'PRIMARY', columns: ['id'] },
      options: { engine: 'InnoDB' },
    });
    state = addRelation(created.state, MY, { child: 'invoices', parent: 'orders' }).state;
    state = renameTable(state, MY, 'customers', 'clients');
    state = updateColumn(state, MY, 'clients', 'name', { name: 'full_name' });
    // MySQL DDL commits as it goes: foreign key checks are off while the script runs.
    expect(modelScript(state, shopMysql(), MY).statements).toEqual([
      'SET FOREIGN_KEY_CHECKS = 0',
      'RENAME TABLE `customers` TO `clients`',
      'ALTER TABLE `clients` CHANGE COLUMN `name` `full_name` varchar(100) NOT NULL',
      'CREATE TABLE `invoices` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `order_id` bigint NOT NULL,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB',
      'ALTER TABLE `invoices` ADD CONSTRAINT `invoices_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`)',
      'SET FOREIGN_KEY_CHECKS = 1',
    ]);
  });

  it('validates the tables it adds or changes with the table designer’s rules', () => {
    let state = startModel(shop(), PG);
    state = updateColumn(state, PG, 'orders', 'total', { dataType: 'numbr(10,2)' });
    state = addTable(state, PG, 'notes').state;
    state = addColumn(state, PG, 'notes', {
      name: 'body',
      dataType: 'text',
      default: 'now(',
    }).state;
    const issues = validateModel(state, shop(), PG);
    expect(issues).toContainEqual(
      expect.objectContaining({ table: 'orders', column: 'total', severity: 'error' }),
    );
    // Untouched tables are not validated again.
    expect(issues.every((i) => i.table === 'orders' || i.table === 'notes')).toBe(true);
  });

  it('comments tables, and names referencing columns in the singular', () => {
    const state = setTableComment(startModel(shop(), PG), PG, 'orders', ' What was bought ');
    expect(findTable(state, PG, 'orders').comment).toBe('What was bought');
    expect(script(state, shop())).toContain(
      `COMMENT ON TABLE "public"."orders" IS 'What was bought'`,
    );
    expect(
      findTable(setTableComment(state, PG, 'orders', ''), PG, 'orders').comment,
    ).toBeUndefined();
    expect(
      ['customers', 'categories', 'addresses', 'boxes', 'statuses', 'analysis', 'data'].map(
        singular,
      ),
    ).toEqual(['customer', 'category', 'address', 'box', 'status', 'analysis', 'data']);
  });
});
